package com.kodilla.exception.main;

import com.kodilla.exception.test.SecondChallenge;

public class ExceptionModuleRunner {

    public static void main(String[] args) {

        SecondChallenge secondChallenge = new SecondChallenge();

        // secondChallenge.probablyIWillThrowException(1.5,1.3);

    }
}
